final_proyecto_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FinalProyectoBundle:Default:index }
final_proyecto_home:
    pattern:  /home
    defaults: { _controller: FinalProyectoBundle:Default:home }
final_proyecto_start_session:
    pattern:  /startSession
    defaults: { _controller: FinalProyectoBundle:Default:startSession }
final_proyecto_close_session:
    pattern:  /closeSession
    defaults: { _controller: FinalProyectoBundle:Default:closeSession }
final_proyecto_show_map:
    pattern:  /showMap
    defaults: { _controller: FinalProyectoBundle:Proyect:showMap }
final_proyecto_get_markers:
    pattern:  /getMarkers
    defaults: { _controller: FinalProyectoBundle:Proyect:getProjectMarkers }
final_proyecto_add_marker:
    pattern:  /addMarker
    defaults: { _controller: FinalProyectoBundle:Proyect:addProjectMarker }
final_proyecto_delete_marker:
    pattern:  /deleteMarker
    defaults: { _controller: FinalProyectoBundle:Proyect:deleteProjectMarker }

